include:
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_right
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: settings_reset
